export const GET_RANKINGS = "";
export const FETCH_RANKINGS_REQUEST = "FETCH_RANKINGS_REQUEST";
export const FETCH_RANKINGS_SUCCESS = "FETCH_RANKINGS_SUCCESS";
export const FETCH_RANKINGS_FAILURE = "FETCH_RANKINGS_FAILURE";
