export const GET_USER_MATCHES = "GET_USER_MATCHES";
export const FETCH_USER_MATCHES_REQUEST = "FETCH_USER_MATCHES_REQUEST";
export const FETCH_USER_MATCHES_SUCCESS = "FETCH_USER_MATCHES_SUCCESS";
export const FETCH_USER_MATCHES_FAILURE = "FETCH_USER_MATCHES_FAILURE";
